apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: vnha2a3s3-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/vnha2a3s3-java-quarkus-gitops